### ISSUE TITLE
The declaration file for types isn't part of the package

### ISSUE THREAD

**Issue by adescre** [voxtok/react-native-ssdp#1]
This isn't immediately a code issue, but could you enable the -d option on the typescript compiler during the build to produce the declaration file for types?
That option is disabled by default sadly.

**Edit**: I just realized that the tsconfig.json already has the declaration option set to true, and a default build produces the .d.ts files. Could is be a packaging issue?

**Comment by fveilly** [comment]
Indeed the declarations files was missing. It should work now.
